export const PLACE_CARDS = [
  {
    id: 1,
    mark: `Premium`,
    href: `#`,
    src: `img/apartment-01.jpg`,
    price: `€120`,
    priceText: `night`,
    isBookmark: false,
    rating: 4,
    name: `Beautiful & luxurious apartment at great location`,
    type: `Apartment`,
  },
  {
    id: 2,
    href: `#`,
    src: `img/room.jpg`,
    price: `€80`,
    priceText: `night`,
    isBookmark: true,
    rating: 4,
    name: `Wood and stone place`,
    type: `Private room`,
  },
  {
    id: 3,
    href: `#`,
    src: `img/apartment-02.jpg`,
    price: `€132`,
    priceText: `night`,
    hasBookmark: false,
    rating: 4,
    name: `Canal View Prinsengracht`,
    type: `Apartment`,
  },
  {
    id: 4,
    mark: `Premium`,
    href: `#`,
    src: `img/apartment-03.jpg`,
    price: `€180`,
    priceText: `night`,
    hasBookmark: false,
    rating: 5,
    name: `Nice, cozy, warm big bed apartment`,
    type: `Apartment`,
  },
  {
    id: 5,
    href: `#`,
    src: `img/room.jpg`,
    price: `€80`,
    priceText: `night`,
    hasBookmark: false,
    rating: 4,
    name: `Nice, cozy, warm big bed apartment`,
    type: `Private room`,
  },
];

export const PLACES_COUNT = 312;
